//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Druzhin1.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guard
    {
        public int GuardID { get; set; }
        public string FullName { get; set; }
        public string Position { get; set; }
        public int PostID { get; set; }
        public Nullable<int> TimeJob { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual DutyLog DutyLog { get; set; }
        public virtual Post Post { get; set; }
        public virtual ReportLog ReportLog { get; set; }
    }
}
